
services:

  postgres:

    image: postgres:17

    container_name: uptime_postgres

    restart: always

    environment:
      POSTGRES_DB: uptime_monitor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d uptime_monitor"]
      interval: 5s
      timeout: 5s
      retries: 10

  fastapi:

    build: .

    container_name: uptime_monitor

    restart: always

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8000:8000"

    env_file:
      - backend/.env

volumes:
  postgres_data:
